### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by z-tech** [codenotary/merkletree#4]
What's the difference between this line https://github.com/codenotary/merkletree/blob/master/tree_test.go#L64 and this line https://github.com/codenotary/merkletree/blob/master/tree_test.go#L58 (when index = 0).

In my language hash of empty string `digest(Algorithm::SHA256, b"")` => `[227, 176, 196, 66, 152, 252, 28, 20, 154, 251, 244, 200, 153, 111, 185, 36, 39, 174, 65, 228, 100, 155, 147, 76, 164, 149, 153, 27, 120, 82, 184, 85]`

but in the `testRoots` object the zeroeth index is => `[219, 52, 38, 232, 120, 6, 141, 40, 210, 105, 182, 200, 113, 114, 50, 44, 229, 55, 43, 101, 117, 109, 7, 137, 0, 29, 52, 131, 95, 96, 28, 3]`

Shouldn't these be the same?

**Comment by z-tech** [comment]
Amazing. Thanks lol. I was able to fix. The work I'm doing at the moment is part of grad school.

Very cool, I'll take a peek. Just out of curiosity, what were some of the reasons for wanting a new implementation?

**Comment by jeroiraz** [comment]
There're two new hash tree implementations:
https://github.com/codenotary/immudb/tree/master/embedded/htree is meant for fixed-size hash trees, we're using it for building a hash tree per transaction i.e. the number of entries is known at commit time.

https://github.com/codenotary/immudb/tree/master/embedded/ahtree is an incremental hash tree backed by append-only files.

**Comment by z-tech** [comment]
Sweet, thanks for the info!
